# Generated by Django 3.0.2 on 2020-07-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Mobile_No', models.CharField(max_length=50)),
                ('Age', models.TextField(max_length=300)),
                ('mean_radius', models.CharField(max_length=50)),
                ('mean_texture', models.CharField(max_length=50)),
                ('mean_perimeter', models.CharField(max_length=50)),
                ('mean_area', models.CharField(max_length=50)),
                ('mean_smoothness', models.CharField(max_length=50)),
                ('Test_Result', models.CharField(max_length=50)),
            ],
        ),
    ]
