# Generated by Django 3.0.2 on 2020-07-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_data',
            name='Age',
            field=models.CharField(max_length=300),
        ),
    ]
