# Generated by Django 3.0.2 on 2020-07-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DS_APP', '0002_auto_20200702_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_data',
            name='Patient_Id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
